# Load the library limma to visualize plots of DE
library(limma)

# Load and save the the RSE object procceded and ready for the DE analysis
rse_gene_SRP130963_DE_ready <- readRDS(
  file = "processed-data/rse_gene_SRP130963_DE_ready"
)

# Load and save the counts in logCPM (object created with voom())
vGene <- readRDS(
  file = "processed-data/vGene_DE_ready"
) 

# Given the linear model fit from lmFit, compute the statistics and log-odds 
# of differential expression by empirical Bayes moderation 
bayes_mod_results <- eBayes(lmFit(vGene))

# Use the results generated by the Bayes moderation to create a table with the results
DE_results <- topTable(
  bayes_mod_results,
  coef = 2,
  number = nrow(rse_gene_SRP130963_DE_ready),
  sort.by = "none"
)

# Check the dimensions of the previous table
# > dim(DE_results)
# Or check the names of the columns of the table
# Several statistics about the DE were calculated by eBayes() and in the table were
# ordered
# [1] "source"      "type"        "bp_length"   "phase"       "gene_id"     "gene_type"  
# [7] "gene_name"   "level"       "mgi_id"      "havana_gene" "tag"         "logFC"      
# [13] "AveExpr"     "t"           "P.Value"     "adj.P.Val"   "B" 
# As seen important stadistical values were calculated like P.value and the adjusted P-value
# The logFC is the Fold Change in logarith of the expression

# Choosing the conventinal alpha cutoff of 0.05, it is possible to quickly summarize
# the number DE genes between the variables, in this case of the tissue type
# > table(DE_results$adj.P.Val < .05)
# FALSE  TRUE 
# 19006  3251 
# This proportion is expected as in the early plot of variancePartition showed 
# low total variance explained by the tissue, but still 3251 were correctly identified
# to have a DE > .05 between tissue type

