# Load the library limma to visualize plots of DE
library(limma)

# Load and save the the RSE object procceded and ready for the DE analysis
rse_gene_SRP130963_DE_ready <- readRDS(
  file = "processed-data/rse_gene_SRP130963_DE_ready"
)

# Load and save the counts in logCPM (object created with voom())
vGene <- readRDS(
  file = "processed-data/vGene_DE_ready"
) 

# Given the linear model fit from lmFit, compute the statistics and log-odds 
# of differential expression by empirical Bayes moderation 
bayes_mod_results <- eBayes(lmFit(vGene))

# Use the results generated by the Bayes moderation to create a table with the results
DE_results <- topTable(
  bayes_mod_results,
  coef = 2,
  number = nrow(rse_gene_SRP130963_DE_ready),
  sort.by = "none"
)

# Check the dimensions of the previous table
# > dim(DE_results)
# Or check the names of the columns of the table
# Several statistics about the DE were calculated by eBayes() and in the table were
# ordered
# [1] "source"      "type"        "bp_length"   "phase"       "gene_id"     "gene_type"  
# [7] "gene_name"   "level"       "mgi_id"      "havana_gene" "tag"         "logFC"      
# [13] "AveExpr"     "t"           "P.Value"     "adj.P.Val"   "B" 
# As seen important stadistical values were calculated like P.value and the adjusted P-value
# The logFC is the Fold Change in logarith of the expression

# Choosing the conventinal alpha cutoff of 0.05, it is possible to quickly summarize
# the number DE genes between the variables, in this case of the tissue type
# > table(DE_results$adj.P.Val < .05)
# FALSE  TRUE 
# 19006  3251 
# This proportion is expected as in the early plot of variancePartition showed 
# low total variance explained by the tissue, but still 3251 were correctly identified
# to have a DE > .05 between tissue type

# See in plots the results of the bayes moderation

# Load ggplot2
library(ggplot2)

# Decide by the adjusted P-value the color
DE_results$significance <- ifelse(DE_results$adj.P.Val < 0.05 & DE_results$logFC > 1, "Up", 
ifelse(DE_results$adj.P.Val < 0.05 & DE_results$logFC < -1, "Down", "NonSig"))

# Plot of logFC and Avarage log-expression
ggplot(DE_results, aes(x = AveExpr, y = logFC, color = significance)) +
  geom_point(alpha = 0.5, size = 1) +
  scale_color_manual(values = c("Up" = "red", "Down" = "blue", "NS" = "grey")) +
  geom_hline(yintercept = c(-1, 1), linetype = "dashed") +
  theme_bw() +
  labs(title = "MA Plot", x = "Average Expression", y = "Log Fold Change")

# Load of ggrepel that allow us to have tags not over themselves 
library(ggrepel)
# Load the library patchwork to combine in one plot 
library(patchwork)

# Check coefficients of the bayes model
# colnames(bayes_mod_results$coefficients)
# [1] "(Intercept)"                                               
# [2] "sra_attribute.tissuedifferentiating ESCs into Neural Cells"
# [3] "sra_attribute.tissueEmbryoid bodies"                       
# [4] "sra_attribute.tissueEpiblast SCs"                          
# [5] "assigned_gene_prop"


# The intercept is taken as the coefficient 1
# The tag is need to be the same or mean the same as the coefficent
comparisons <- list(
  list(coef = 2, title = "ESCs vs Neural Cells"),
  list(coef = 3, title = "ESCs vs Embryoid Bodies"),
  list(coef = 4, title = "ESCs vs Epiblast SCs")
)

# This funtions takes the coefficient number and the label of the plot
# It does a vulcano plot with cutoffs to logFC > 1 and pvalue to be at least .05
make_volcano <- function(coef_num, title_label, top_x) {
  
  df <- topTable(bayes_mod_results, coef = coef_num, number = Inf, sort.by = "none")
  df$gene_name <- DE_results$gene_name  
  
  # Define the stadistical cutoff
  # In this case .05 and logFC > 1 was set
  df$significant <- df$adj.P.Val < 0.05 & abs(df$logFC) > 1
  # Complete with NA when the condition is not met
  df$color_val   <- ifelse(df$significant, -log10(df$adj.P.Val), NA)
  
  # Show the most stadistical significant genes 
  top <- head(df[order(df$adj.P.Val), ], top_x)
  
  ggplot(df, aes(x = logFC, y = -log10(P.Value))) +
    # Non significant points
    geom_point(data = subset(df, !significant),
               color = "lightgray", alpha = 0.2, size = 1) +
    # Significant ponints, form a grandient
    geom_point(data = subset(df, significant),
               aes(color = color_val), size = 1.5) +
    scale_color_gradient(low = "blue", high = "red",
                         name = "-log10\n(Adj.P)") +
    # Top tags defined earlier
    geom_text_repel(data = top,
                    aes(label = gene_name),
                    size = 3, fontface = "bold",
                    box.padding = 0.5) +
    # Reference lines of the cutoffs
    geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "darkgrey") +
    geom_vline(xintercept = c(-1, 1),     linetype = "dashed", color = "darkgrey") +
    theme_minimal(base_size = 11) +
    labs(title = title_label,
         x = "Log2 Fold Change",
         y = "-log10(P-Value)")
}

# Call to the vulcano maker plot
# Top_n definition
take_top_n <- 4
p1 <- make_volcano(2, "ESCs vs Neural Cells", take_top_n)
p2 <- make_volcano(3, "ESCs vs Embryoid Bodies", take_top_n)
p3 <- make_volcano(4, "ESCs vs Epiblast SCs", take_top_n)

# Join all vulcano plots
(p1 | p2 | p3) +
  plot_annotation(
    title = "Vulcano Plots: ESCs vs Other Tissues",
    theme = theme(plot.title = element_text(size = 14, face = "bold", hjust = 0.5))
  ) +
  # Uniq for the color tag
  plot_layout(guides = "collect") 


top_neural <- topTable(bayes_mod_results, coef = 2, number = take_top_n)
top_embryoid <- topTable(bayes_mod_results, coef = 3, number = take_top_n)
top_epiblast <- topTable(bayes_mod_results, coef = 4, number = take_top_n)

# Show top tables
top_neural
top_embryoid
top_epiblast

# DE_results[DE_results$gene_name %in% top_significant_genes, ]
